In [37]:
# Task- Create arrays for sales, price, cost
import numpy as np
sales=np.array([[50,30,20],[60,35,25],[55,32,22],[70,40,30],[65,38,28],[80,45,35]])
sp=[100,150,200]
c=[60,90,140]
prod=["A","B","C"]
mon=[1,2,3,4,5,6]

In [38]:
print(sales)

[[50 30 20]
 [60 35 25]
 [55 32 22]
 [70 40 30]
 [65 38 28]
 [80 45 35]]


In [39]:
prod_sales=np.sum(sales,axis=0)
print("Total sales volume:")
for i in range(len(prod_sales)):
    print(f"Product {prod[i]} : {prod_sales[i]}")

Total sales volume:
Product A : 380
Product B : 220
Product C : 160


In [40]:
#  Calculate monthly revenue
rev=sales*sp
mon_rev=np.sum(rev,axis=1)
print("monthly revenue")
for i in range(len(mon_rev)):
    print(f"Month {mon[i]} : {mon_rev[i]}")

monthly revenue
Month 1 : 13500
Month 2 : 16250
Month 3 : 14700
Month 4 : 19000
Month 5 : 17800
Month 6 : 21750


In [41]:
# Calculate monthly total cost
cost=sales*c
mon_cos=np.sum(cost,axis=1)
print("monthly cost")
for i in range(len(mon_cos)):
    print(f"Month {mon[i]} : {mon_cos[i]}")

monthly cost
Month 1 : 8500
Month 2 : 10250
Month 3 : 9260
Month 4 : 12000
Month 5 : 11240
Month 6 : 13750


In [42]:
# Calculate profit matrix
profit=rev-cost
print("profit matrix:\n",profit)

profit matrix:
 [[2000 1800 1200]
 [2400 2100 1500]
 [2200 1920 1320]
 [2800 2400 1800]
 [2600 2280 1680]
 [3200 2700 2100]]


In [43]:
# Find total profit per product
t_pr_p=np.sum(profit,axis=0)
print("Total profit per product:")
for i in range(len(t_pr_p)):
    print(f"product {prod[i]} : {t_pr_p[i]}")

Total profit per product:
product A : 15200
product B : 13200
product C : 9600


In [44]:
# Find most profitable product
print(f"Most profitable product: Product{prod[np.argmax(t_pr_p)]}")

Most profitable product: ProductA


In [45]:
# Find profit per month
t_pr_m=np.sum(profit,axis=1)
print("profit per month:") 
for i in range(len(t_pr_m)):
    print(f"Month {mon[i]} : {t_pr_m[i]}")

profit per month:
Month 1 : 5000
Month 2 : 6000
Month 3 : 5440
Month 4 : 7000
Month 5 : 6560
Month 6 : 8000


In [46]:
# Identify best month (highest profit)
print(f"Most profitable Month: Month {mon[np.argmax(t_pr_m)]}")

Most profitable Month: Month 6


In [47]:
rev_p=np.sum(rev,axis=0)

In [48]:
# Calculate profit margin per product
mar=t_pr_p/rev_p
print("Profit Margin")
for i in range(len(rev_p)):
    print(f"Product {prod[i]} : {mar[i]}")

Profit Margin
Product A : 0.4
Product B : 0.4
Product C : 0.3


In [49]:
mon_rev

array([13500, 16250, 14700, 19000, 17800, 21750])

In [50]:
# Calculate month-to-month revenue growth (%)
growth=((mon_rev[1:]-mon_rev[:-1])/mon_rev[:-1])*100

In [51]:
for i in range(len(growth)):
    print(f"Month{mon[i]} :{growth[i]}")

Month1 :20.37037037037037
Month2 :-9.538461538461538
Month3 :29.25170068027211
Month4 :-6.315789473684211
Month5 :22.191011235955056


In [52]:
# Identify which month had highest growth
print(f"Highest Growth: Month {mon[np.argmax(growth)]}   -->  Month {mon[np.argmax(growth)]+1}")

Highest Growth: Month 3   -->  Month 4


# So , the company should promote Product - A